"""Verify the SQLAlchemy metadata exposes the current product tables."""

from brain.platform.db.base import Base
from brain.platform.db.models import *  # noqa


EXPECTED_TABLES = {
    "action_manifests",
    "agent_api_calls",
    "agent_run_artifacts",
    "agent_run_events",
    "agent_runs",
    "agent_sessions",
    "browser_pool_entries",
    "browser_sessions",
    "chat_conversation_members",
    "chat_conversation_reads",
    "chat_conversations",
    "chat_message_mentions",
    "chat_messages",
    "chat_notifications",
    "consolidation_runs",
    "cortex_events",
    "cycle_guidance",
    "cycle_failure_guard_latches",
    "cycle_failure_guard_observations",
    "cycle_output_targets",
    "cycle_revisions",
    "cycle_run_evaluations",
    "cycle_runs",
    "cycles",
    "daily_metrics",
    "domain_events",
    "domain_field_definitions",
    "domain_object_types",
    "domain_records",
    "domain_relation_types",
    "domain_relations",
    "domains",
    "environment_bindings",
    "environment_commands",
    "environment_services",
    "error_pipeline_runs",
    "external_agent_connection_tokens",
    "external_agent_connections",
    "external_agent_task_artifacts",
    "external_agent_task_events",
    "external_agent_tasks",
    "inbound_decision_receipts",
    "inbound_domain_projection_keys",
    "inbound_domain_projections",
    "inbound_events",
    "inbound_source_policies",
    "launch_handoffs",
    "packet_brief_deliveries",
    "idea_connections",
    "idea_project_attachments",
    "idea_state_log",
    "idea_threads",
    "ideas",
    "memory_assertions",
    "memory_edges",
    "memory_health_log",
    "memory_node_embeddings",
    "memory_nodes",
    "memory_sources",
    "memory_spans",
    "knowledge_item_embeddings",
    "knowledge_items",
    "knowledge_sync_state",
    "narrative_sessions",
    "notification_events",
    "object_references",
    "obligation_notices",
    "open_asks",
    "org_api_keys",
    "orgs",
    "project_narratives",
    "project_profile_access",
    "project_profiles",
    "provider_alert_ledger",
    "provider_alert_occurrences",
    "provider_alert_surges",
    "provider_health_snapshots",
    "resource_leases",
    "reconstruction_evidence",
    "reconstruction_feedback",
    "reconstruction_runs",
    "reconstruction_steps",
    "retrieval_decisions",
    "retrieval_item_feedback",
    "retrieval_log",
    "retrieval_pool_stats",
    "routing_decisions",
    "routing_experiments",
    "run_target_bindings",
    "scheduler_failure_guard_latches",
    "scheduler_jobs",
    "scheduler_leases",
    "scheduler_run_steps",
    "scheduler_runs",
    "secrets",
    "session_scratchpad",
    "skill_assets",
    "skill_bundle_versions",
    "skill_bundles",
    "skill_dependencies",
    "skill_executions",
    "skill_heuristics",
    "skill_installations",
    "skill_overlays",
    "skill_run_evidence",
    "skill_versions",
    "skills",
    "target_registry",
    "thread_context_submissions",
    "thread_discussion_comments",
    "user_codex_connections",
    "user_mentions",
    "users",
    "vault_access_log",
    "vault_agent_grants",
    "vault_config",
    "vault_missing_requests",
    "vault_project_bindings",
    "vault_sessions",
    "visual_blocks",
    "workspace_app_events",
    "workspace_app_states",
    "workspace_app_versions",
    "workspace_apps",
    "workspace_pins",
    "workspace_pool_entries",
    "workspace_tool_installations",
    "workspace_tool_user_configs",
}


def _modeled_tables() -> set[str]:
    return {
        table
        for table in Base.metadata.tables
        if not table.startswith("_test_")
    }


def test_all_tables_modeled():
    missing = EXPECTED_TABLES - _modeled_tables()
    assert not missing, f"Missing models for tables: {missing}"


def test_no_extra_tables():
    extra = _modeled_tables() - EXPECTED_TABLES
    assert not extra, f"Unexpected tables registered: {extra}"


def test_table_count():
    assert len(_modeled_tables()) == len(EXPECTED_TABLES)
