from __future__ import annotations

import json
from unittest.mock import AsyncMock, patch

import pytest

from brain.systems.cortex.project_context.github import (
    GitHubConnectorError,
    async_create_repo_issue,
)
from brain.systems.runs.execution_context import bind_agent_context
from brain.systems.runs.tool_catalog.handlers.github import _handle_create_github_issue


_H = "brain.systems.runs.tool_catalog.handlers.github"


def test_customer_bug_contract_is_in_run_visible_github_tool_guidance():
    from brain.systems.runs.tool_catalog.definitions.github import GITHUB_TOOLS

    definition = next(tool for tool in GITHUB_TOOLS if tool["name"] == "create_github_issue")
    guidance = definition["description"]

    assert "Customer-reported bug filing is a two-part contract" in guidance
    assert "GitHub issue in the owning repo as the durable artifact" in guidance
    assert "linked mirror in an existing workspace tracker" in guidance
    assert "Never create a Domain while filing" in guidance
    assert "customer quote, concrete impact, and source origin_ref" in guidance
    assert "final reply must name the GitHub issue and the exact blocker" in guidance


def _vault_patches(*, bound_env: dict, secrets: list, get_secret=None):
    """Patch the three Vault seams the handler resolves tokens through."""
    return (
        patch(f"{_H}.async_resolve_project_bound_env_tokens", new=AsyncMock(return_value=bound_env)),
        patch(f"{_H}.async_list_secrets", new=AsyncMock(return_value=secrets)),
        patch(f"{_H}.async_get_secret", new=AsyncMock(side_effect=get_secret or (lambda *a, **k: None))),
    )


@pytest.mark.asyncio
async def test_create_github_issue_happy_path_opens_real_issue():
    created = {
        "repo": "uwear-ai/uwear-backend",
        "issue": {"type": "issue", "number": 321, "html_url": "https://github.com/uwear-ai/uwear-backend/issues/321"},
    }
    p1, p2, p3 = _vault_patches(bound_env={"GITHUB_TOKEN": "write-token"}, secrets=[])
    with bind_agent_context({"user_id": "u", "org_id": "o"}), p1, p2, p3, patch(
        f"{_H}.async_create_repo_issue",
        new=AsyncMock(return_value=created),
    ) as create:
        result = await _handle_create_github_issue(
            repo="https://github.com/uwear-ai/uwear-backend.git",
            title="MissingGreenlet in GenerationRead.location",
            body="> *This was generated by AI during triage.*\nDetails.",
            labels=["bug"],
            assignees=["reda"],
        )

    payload = json.loads(result)
    assert payload["repo"] == "uwear-ai/uwear-backend"
    assert payload["issue"]["number"] == 321
    assert payload["token_source"] == "project_binding:GITHUB_TOKEN"
    create.assert_awaited_once()
    assert create.await_args.args == ("uwear-ai/uwear-backend",)
    assert create.await_args.kwargs["title"] == "MissingGreenlet in GenerationRead.location"
    assert create.await_args.kwargs["labels"] == ["bug"]
    assert create.await_args.kwargs["assignees"] == ["reda"]
    assert create.await_args.kwargs["token"] == "write-token"


@pytest.mark.asyncio
async def test_create_github_issue_returns_no_write_token_when_no_token_resolves():
    # No bound context → the Vault lookup block is skipped, leaving only the
    # public (token=None) candidate, which a write must never use.
    with patch(f"{_H}.async_create_repo_issue", new=AsyncMock()) as create:
        result = await _handle_create_github_issue(
            repo="uwear-ai/uwear-backend",
            title="Some incident",
        )

    payload = json.loads(result)
    # Contract, not copy: a write with no App identity is flagged no_write_token,
    # returns a non-empty actionable error, and never opens an issue. The exact
    # wording is free to change without breaking this test.
    assert payload["no_write_token"] is True
    assert payload["repo"] == "uwear-ai/uwear-backend"
    assert isinstance(payload.get("error"), str) and payload["error"].strip()
    create.assert_not_awaited()


@pytest.mark.asyncio
async def test_create_github_issue_private_repo_404_degrades_gracefully():
    p1, p2, p3 = _vault_patches(bound_env={"GITHUB_TOKEN": "public-only-token"}, secrets=[])
    with bind_agent_context({"user_id": "u", "org_id": "o"}), p1, p2, p3, patch(
        f"{_H}.async_create_repo_issue",
        new=AsyncMock(
            side_effect=GitHubConnectorError(
                status_code=404,
                message="Repository not found or not visible to this token.",
            )
        ),
    ):
        result = await _handle_create_github_issue(
            repo="uwear-ai/uwear-backend",
            title="Private repo write",
        )

    payload = json.loads(result)
    assert payload["status_code"] == 404
    assert payload["no_write_token"] is True
    assert payload["repo"] == "uwear-ai/uwear-backend"


@pytest.mark.asyncio
async def test_create_github_issue_requires_title():
    with patch(f"{_H}.async_create_repo_issue", new=AsyncMock()) as create:
        result = await _handle_create_github_issue(repo="uwear-ai/uwear-backend", title="   ")
    payload = json.loads(result)
    assert "non-empty title" in payload["error"]
    create.assert_not_awaited()


@pytest.mark.asyncio
async def test_create_github_issue_rejects_bad_repo_slug():
    with patch(f"{_H}.async_create_repo_issue", new=AsyncMock()) as create:
        result = await _handle_create_github_issue(repo="not a repo", title="X")
    payload = json.loads(result)
    assert "owner/name" in payload["error"]
    create.assert_not_awaited()


@pytest.mark.asyncio
async def test_create_github_issue_write_ignores_arbitrary_personal_github_secret():
    # A read may fall back to any available github-ish secret, but a public write
    # must NOT auto-author under an arbitrary teammate PAT. Only the canonical
    # GITHUB_TOKEN/GH_TOKEN default (or an explicit key / project binding) is a
    # valid write identity, so with only GITHUB_TOKEN_ALICE present the write has
    # no candidate and degrades to no_write_token.
    async def fake_get_secret(key_name, *args, **kwargs):
        return {"GITHUB_TOKEN_ALICE": "alice-pat"}.get(key_name)

    async def fake_list_secrets(*args, **kwargs):
        return [{"key_name": "GITHUB_TOKEN_ALICE", "category": "github", "agent_access_level": "available"}]

    with bind_agent_context({"user_id": "u", "org_id": "o"}), patch(
        f"{_H}.async_resolve_project_bound_env_tokens", new=AsyncMock(return_value={})
    ), patch(
        f"{_H}.async_list_secrets", new=AsyncMock(side_effect=fake_list_secrets)
    ), patch(
        f"{_H}.async_get_secret", new=AsyncMock(side_effect=fake_get_secret)
    ), patch(f"{_H}.async_create_repo_issue", new=AsyncMock()) as create:
        result = await _handle_create_github_issue(repo="uwear-ai/uwear-backend", title="X")

    payload = json.loads(result)
    assert payload["no_write_token"] is True
    create.assert_not_awaited()


@pytest.mark.asyncio
async def test_connector_posts_issue_with_only_set_fields():
    fake_created = {"number": 7, "html_url": "https://github.com/uwear-ai/uwear-backend/issues/7", "title": "X"}
    with patch(
        "brain.systems.cortex.project_context.github._async_request",
        new=AsyncMock(return_value=fake_created),
    ) as request:
        payload = await async_create_repo_issue(
            "uwear-ai/uwear-backend",
            title="X",
            body="",  # empty body must be omitted
            labels=["bug", "  "],
            assignees=[],
            token="write-token",
        )

    assert payload["repo"] == "uwear-ai/uwear-backend"
    assert payload["issue"]["number"] == 7
    request.assert_awaited_once()
    assert request.await_args.args[1] == "POST"
    assert request.await_args.args[2] == "/repos/uwear-ai/uwear-backend/issues"
    assert request.await_args.kwargs["token"] == "write-token"
    body = request.await_args.kwargs["json"]
    assert body == {"title": "X", "labels": ["bug"]}  # empty body/assignees dropped


@pytest.mark.asyncio
async def test_connector_rejects_empty_title():
    with pytest.raises(GitHubConnectorError) as exc:
        await async_create_repo_issue("uwear-ai/uwear-backend", title="   ")
    assert exc.value.status_code == 422
