#!/bin/bash
# Deploy illo-brain without killing active AgentRuns.
# Usage: ./ops/deploy.sh
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)
PYTHON_BIN="$ROOT/venv/bin/python3"

runtime_env_file_path() {
  if [ -n "${ILLO_RUNTIME_ENV_FILE:-}" ]; then
    case "$ILLO_RUNTIME_ENV_FILE" in
      /*) echo "$ILLO_RUNTIME_ENV_FILE" ;;
      *) echo "$ROOT/$ILLO_RUNTIME_ENV_FILE" ;;
    esac
    return 0
  fi

  local private_home="${ILLO_PRIVATE_HOME:-.illo}"
  case "$private_home" in
    /*) echo "$private_home/runtime.env" ;;
    *) echo "$ROOT/$private_home/runtime.env" ;;
  esac
}

production_env_file_path() {
  if [ -n "${ILLO_PRODUCTION_ENV_FILE:-}" ]; then
    case "$ILLO_PRODUCTION_ENV_FILE" in
      /*) echo "$ILLO_PRODUCTION_ENV_FILE" ;;
      *) echo "$ROOT/$ILLO_PRODUCTION_ENV_FILE" ;;
    esac
    return 0
  fi

  echo "$HOME/.config/illo-brain/production.env"
}

source_env_file_defaults() {
  local file="$1"
  local preserve_empty="${2:-1}"
  [ -f "$file" ] || return 0

  local keys=()
  local had=()
  local values=()
  local line trimmed key idx

  while IFS= read -r line || [ -n "$line" ]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    if [[ "$trimmed" =~ ^(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)= ]]; then
      key="${BASH_REMATCH[2]}"
      keys+=("$key")
      if [ "${!key+x}" = "x" ] && { [ "$preserve_empty" = "1" ] || [ -n "${!key}" ]; }; then
        had+=("1")
        values+=("${!key}")
      else
        had+=("0")
        values+=("")
      fi
    fi
  done < "$file"

  set -a
  source "$file" 2>/dev/null || true
  set +a

  for idx in "${!keys[@]}"; do
    if [ "${had[$idx]}" = "1" ]; then
      export "${keys[$idx]}=${values[$idx]}"
    fi
  done
}

source_deploy_env() {
  source_env_file_defaults "$(production_env_file_path)" 0
  source_env_file_defaults ".env"
  source_env_file_defaults "$(runtime_env_file_path)" 0
}

sync_production_service_env() {
  local env_file dotenv_file runtime_file
  env_file="$(production_env_file_path)"
  dotenv_file="$ROOT/.env"
  runtime_file="$(runtime_env_file_path)"

  mkdir -p "$(dirname "$env_file")"
  "$PYTHON_BIN" - "$env_file" "$dotenv_file" "$runtime_file" <<'PY'
import os
import re
import sys
from collections import OrderedDict
from pathlib import Path

env_path = Path(sys.argv[1])
source_paths = [Path(item) for item in sys.argv[2:]]
assignment = re.compile(r"^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
required_keys = (
    "DATABASE_URL", "DB_URL", "BRAIN_DB_URL", "DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD",
    "SECRET_KEY", "VAULT_MASTER_KEY", "FLASK_SECRET_KEY", "OPENCLAW_GATEWAY_TOKEN", "ILLO_API_TOKEN",
    "EMBEDDING_BACKEND", "EMBEDDING_DIM", "EMBEDDING_API_PROVIDER", "EMBEDDING_API_MODEL",
    "EMBEDDING_API_KEY", "EMBEDDING_CPU_MODEL", "EMBEDDING_MODEL", "EMBEDDING_MODEL_PATH",
    "MEMORY_RERANKER", "OPENAI_API_KEY", "OPENAI_ORG_ID", "OPENAI_PROJECT",
)

def parse_value(raw: str) -> str:
    value = raw.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value

def read_assignments(path: Path) -> OrderedDict[str, str]:
    values = OrderedDict()
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = assignment.match(line)
        if match:
            values[match.group(1)] = parse_value(match.group(2))
    return values

def systemd_quote(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_@%+=:,./-]*", value):
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

merged = read_assignments(env_path)
ordered_keys = list(merged)
for path in source_paths:
    for key in read_assignments(path):
        if key not in ordered_keys:
            ordered_keys.append(key)
for key in required_keys:
    if key not in ordered_keys:
        ordered_keys.append(key)

for key in ordered_keys:
    value = os.environ.get(key)
    if value:
        merged[key] = value

env_path.parent.mkdir(parents=True, exist_ok=True)
with env_path.open("w", encoding="utf-8") as handle:
    handle.write("# Generated by ./ops/deploy.sh for Illo Brain user services.\n")
    handle.write("# Keep this file private; it may contain API keys and vault secrets.\n")
    for key, value in merged.items():
        if "\n" in value:
            continue
        handle.write(f"{key}={systemd_quote(value)}\n")
env_path.chmod(0o600)
print(env_path)
PY
}

have_user_service() {
  systemctl --user cat "$1" >/dev/null 2>&1
}

restart_user_service_if_present() {
  local service_name="$1"
  if have_user_service "$service_name"; then
    systemctl --user enable "$service_name"
    systemctl --user restart "$service_name"
    return 0
  fi
  return 1
}

install_user_service() {
  local source_path="$1"
  local dest_path="$HOME/.config/systemd/user/$(basename "$source_path")"
  "$PYTHON_BIN" - "$source_path" "$dest_path" "$ROOT" <<'PY'
import sys
from pathlib import Path

source = Path(sys.argv[1])
dest = Path(sys.argv[2])
root = sys.argv[3]

text = source.read_text(encoding="utf-8").replace("%h/illo-brain", root)
dest.write_text(text, encoding="utf-8")
PY
}

active_agent_run_count() {
  "$PYTHON_BIN" - <<'PY'
from sqlalchemy import func, select

from brain.platform.db.models.agent_run import AgentRunRow
from brain.platform.db.repositories.unit_of_work import UnitOfWork

active = ("starting", "running", "verifying")
with UnitOfWork() as uow:
    count = uow.session.scalar(
        select(func.count()).select_from(AgentRunRow).where(AgentRunRow.status.in_(active))
    )
print(int(count or 0))
PY
}

restart_or_drain_worker() {
  if ! have_user_service cortex-worker; then
    echo "Worker:    missing user service (expected cortex-worker)"
    return 0
  fi

  systemctl --user enable cortex-worker
  local active_runs
  active_runs="$(active_agent_run_count)"
  if [ "$active_runs" = "0" ]; then
    systemctl --user restart cortex-worker
    echo "Worker:    restarted (no active AgentRuns)"
    return 0
  fi

  echo "Worker:    $active_runs active AgentRun(s); signaling drain instead of restart"
  echo "           It will stop claiming new runs and restart on the new version after active runs finish."
  systemctl --user kill --kill-who=main --signal=TERM cortex-worker || true
}

wait_for_embedding_backend() {
  "$PYTHON_BIN" - <<'PY'
import json
import os
import sys
import time
import urllib.request

wait_seconds = int(os.environ.get("EMBEDDING_WORKER_RESTART_TIMEOUT_SECONDS", "7200"))
deadline = time.time() + wait_seconds
last = None
while time.time() < deadline:
    try:
        with urllib.request.urlopen("http://127.0.0.1:9800/health", timeout=3) as resp:
            health = json.load(resp)
        last = health
        worker = health.get("workers", {}).get("embedding", {}) or {}
        if worker.get("status") == "ready":
            sys.exit(0)
        if worker.get("status") == "failed":
            print(f"Embedding backend failed to start: {worker}", file=sys.stderr)
            sys.exit(1)
    except Exception as exc:
        last = str(exc)
    time.sleep(1)

print(f"Embedding backend did not become ready in time after {wait_seconds}s: {last}", file=sys.stderr)
sys.exit(1)
PY
}

echo "=== Pulling latest code ==="
git checkout main
git pull origin main

if [ ! -x "$PYTHON_BIN" ]; then
  echo "=== Creating virtual environment ==="
  python3 -m venv "$ROOT/venv"
fi

source_deploy_env

echo "=== Syncing Python dependencies ==="
"$PYTHON_BIN" -m pip install -r requirements.txt
./ops/install-browser-runtime.sh "$PYTHON_BIN"
./ops/sync-frontend-deps.sh
if [ -d "$ROOT/frontend" ]; then
  echo "=== Building frontend ==="
  (cd "$ROOT/frontend" && npm run build)
fi

echo "=== Running production config doctor ==="
"$PYTHON_BIN" -m brain.app.cli.config_doctor --production --root "$ROOT"

echo "=== Running database migrations ==="
"$PYTHON_BIN" -m alembic upgrade head
echo "  Migrations complete."

echo "=== Syncing production service env ==="
sync_production_service_env
source_deploy_env

echo "=== Installing systemd services ==="
mkdir -p ~/.config/systemd/user
install_user_service ops/cortex-worker.service
install_user_service ops/illo-scheduler.service
if [ -f ops/illo-embed.service ]; then
  install_user_service ops/illo-embed.service
fi
systemctl --user daemon-reload

echo "=== Restarting services ==="
ACTIVE_RUNS="$(active_agent_run_count)"
EMBED_SERVICE=""
if [ "$ACTIVE_RUNS" != "0" ]; then
  if have_user_service illo-embed; then
    EMBED_SERVICE="illo-embed"
  elif have_user_service illo-gpu-server; then
    EMBED_SERVICE="illo-gpu-server"
  fi
  if [ -n "$EMBED_SERVICE" ]; then
    echo "Embedder:  leaving $EMBED_SERVICE running ($ACTIVE_RUNS active AgentRun(s))"
  fi
elif restart_user_service_if_present illo-embed; then
  EMBED_SERVICE="illo-embed"
elif restart_user_service_if_present illo-gpu-server; then
  EMBED_SERVICE="illo-gpu-server"
fi

if [ -n "$EMBED_SERVICE" ] && [ "$ACTIVE_RUNS" = "0" ]; then
  echo "Embedder:  $(systemctl --user is-active "$EMBED_SERVICE")"
  wait_for_embedding_backend
elif [ -z "$EMBED_SERVICE" ]; then
  echo "Embedder:  missing user service (expected illo-embed or illo-gpu-server)"
fi
restart_or_drain_worker
systemctl --user enable illo-scheduler
systemctl --user restart illo-scheduler
if have_user_service illo-dashboard; then
  systemctl --user restart illo-dashboard
elif have_user_service illo-api; then
  systemctl --user restart illo-api
else
  echo "Dashboard: missing user service (expected illo-dashboard or illo-api)"
fi

echo "=== Status ==="
if have_user_service illo-dashboard; then
  echo "Dashboard: $(systemctl --user is-active illo-dashboard)"
elif have_user_service illo-api; then
  echo "API:       $(systemctl --user is-active illo-api)"
else
  echo "Dashboard: missing"
fi
if [ -n "$EMBED_SERVICE" ]; then
  echo "Embedder:  $(systemctl --user is-active "$EMBED_SERVICE")"
else
  echo "Embedder:  missing"
fi
echo "Worker:    $(systemctl --user is-active cortex-worker)"
echo "Scheduler: $(systemctl --user is-active illo-scheduler)"
echo ""
echo "Deploy complete at $(date)"
